# -*- coding: utf-8 -*-
"""Copia de Python_Semana01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvHI8SDKdiCZUDYmj9rk2F18pILqJUmA

# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) ** Python Semana01: Intro** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En estos ejercicios vamos a trabajar cosas que nos permitan empezar a programar usando Python.

La idea es que ustedes vayan resolviendo los ejercicios sin la necesidad de instalarse nada en sus computadoras.
Antes que nada, creen una copia de este archivo en su ***Google Drive*** para tener permisos de edición, luego pueden compartirlo con quien quieran, tengan cuidado con los permisos al momento de compartir!!!!!!!. Si quieren, nos pueden compartir su documento para que ayudemos con las dudas.


### **Profe: xxx@unahur.edu.ar** ###

En los bloques de código como el que les aparece aca abajo, se puede programar en Python, al pararse dentro del bloque, aparecerá un ícono de "*play*" en la esquina superior izquierda, "*clickeando*" en este ícono, se ejecuta el código escrito y se muestra la salida debajo, probemos:
"""

# +, -, *, /, //, %
num1 = float("12")
num2 =1
# esto es una suma

res = num1 + num2
print(res)

# ==, !=, <=, <, >, >=
# or, and, not

precio = "$10"
print(precio)

variableDestino = input("Ingrese un numero: ")

print(type(variableDestino))
print(variableDestino)

"""Una cosa a tener en cuenta es que todos los bloques de código estan conectados entre sí, es por eso que si vemos en el bloque de código de abajo, podemos usar la variable "precio" declarada en el bloque anterior, veamos un ejemplo:"""

#precioConIVA = 1.21*precio
#print(precioConIVA)

varString = int(input("ingrese un nro "))
varInt = int(input("ingrese un nro "))

print(varString + varString)
print(varInt + varInt)
print(varInt + varString)

"""Ahora si, luego de las aclaraciones del caso y sabiendo como escribir y ejecutar código en los bloques de este archivo, empezamos con la guía.

#**Primera parte: Declaración de variables y operaciones básicas**

### **Ejercicio 1**

Primer programa en Python. Escribir un programa que imprima por pantalla "Hola mundo".
"""

print("Hola mundo")

"""### **Ejercicio 2**

Escribir un programa que cargue en una variable la cadena de caracteres “Hola mundo” y luego la imprima por pantalla.
"""

saludo = "Hola mundo"
print(saludo)

"""### **Ejercicio 3**

Escribir un programa que cree dos variables enteras, le cargue números arbitrarios (cualquiera) y muestre por pantalla: la suma, la resta, la multiplicación, la división entera y el resto de la división entera.
"""

num1 = 3
num2 = 4

print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 // num2)
print(num1 % num2)

"""### **Ejercicio 4**

Implementar algoritmos que permitan:


*   Calcular el perímetro y el área de un rectángulo, dada su base y su altura
*   Calcular el perímetro y el área de un círculo dado su radio.

Declarar las variables necesarias y asignarle números arbitrarios
"""

import math
baseRectangulo = 3
alturaRectangulo = 4
radioCirculo = 3
perimetroRectangulo = (baseRectangulo * 2) + (alturaRectangulo * 2)
areaRectangulo = alturaRectangulo * baseRectangulo
areaCirculo = math.pi * math.pow(radioCirculo, 2)
perimetroCirculo = 2 * math.pi * radioCirculo
print(f"El area del rectangulo es {areaRectangulo} y su perimetro es {baseRectangulo}")
print(f"El area del circulo es {areaCirculo} y su perimetro es {perimetroCirculo}")

"""### **Ejercicio 5**

Escribir un programa que pida una temperatura en grados Celsius al usuario, realice la transformación de grados Celsius a Fahrenheit e imprima el resultado por pantalla.
"""

tempCelsius = int(input("Ingrese una temperatura en grados Celsius:"))
tempFarenheit = (tempCelsius - 32) / 1.8
print("La temperatura en grados Fahrenheit es", tempFarenheit)

"""### **Ejercicio 6**

Escribir un programa que pregunte al usuario por el número de horas trabajadas y el costo por hora. Después debe mostrar por pantalla el sueldo que le corresponde.
"""

horasTrabajadas = int(input("Ingrese la cantidad de horas trabajadas:"))
costoPorHora = int(input("Ingrese el costo por hora trabajada:"))
print(f"El sueldo que le corresponde es ${(horasTrabajadas * costoPorHora)}")

"""### **Ejercicio 7**

Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable. Luego debe muestrar por pantalla la frase: "Tu índice de masa corporal es: \<imc>". Donde \<imc> es el índice de masa corporal calculado.
"""

peso = float(input("Ingrse su peso en kg:"))
estatura = float(input("Ingrese su estatura en metros"))
imc = peso / (estatura ** 2)
print("Tu indice de masa corporal es", imc)

"""### **Ejercicio 8**

Escribir un programa que pregunte al usuario una cantidad a invertir, el interés anual y el número de años, y muestre por pantalla el capital obtenido en la inversión.
"""

cantInvertir = float(input("Ingrese la cantidad a invertir:"))
cantInteres = float(input("Ingrese el interes anual:"))
años = int(input("Ingrese el numero de años a invertir:"))
capitalObtenido = (cantInvertir / (cantInteres / 100) * años) - cantInvertir
print(f"El capital obtenido en la inversion es: ${capitalObtenido}")

"""### **Ejercicio 9**

Escribir un programa que pregunte el nombre completo del usuario en la consola y después muestre por pantalla el nombre completo del usuario tres veces, una con todas las letras minúsculas, otra con todas las letras mayúsculas y otra solo con la primera letra del nombre y de los apellidos en mayúscula. El usuario puede introducir su nombre combinando mayúsculas y minúsculas como quiera.
"""

nombre = input("Ingrese su nombre completo: ")
nombMayus = nombre.upper()
nombMinus = nombre.lower()
nombCapital = nombre.title()
print(nombMayus, nombMinus, nombCapital)

"""### **Ejercicio 10**

Escribir un programa que pregunte el nombre del usuario en la consola y después de que el usuario lo introduzca muestre por pantalla: "El \<NOMBRE> tiene \<N> letras", donde \<NOMBRE> es el nombre de usuario en mayúsculas y \<N> es el número de letras que tienen el nombre.
"""

nombre = input("Ingrese su nombre:")
print(f"El nombre {nombre} tiene {len(nombre)} letras")

"""### **Ejercicio 11**

Escribir un programa que pida una palabra al usuario, reeplace todas las letras "a" por "z" y muestre el resultado por pantalla.
"""

palabra = input("Ingrese una palabra:")
print(palabra.replace("a", "z"))

"""### **Ejercicio 12**

Escribir un programa que pida dos palabras al usuario y muestre por pantalla la concatenacion de ambas.  
"""

palabra_uno = input("Ingrese la primer palabra: ")
palabra_dos = input("Ingrese la segunda palabra: ")
print(palabra_uno + palabra_dos)

"""### **Ejercicio 13**

Escribir un programa que pida una palabra y un número N al usuario y muestre por pantalla la palabra ingresada repetida N veces.
"""

palabra = input("Ingrese una palabra:")
cantidad = int(input("Ingrese la cantidad de veces a repetir la palabra:"))
print(palabra * cantidad)

"""#**Segunda parte: Estructuras de control**

### **Ejercicio 14**

Escribir un programa que pregunte al usuario su edad y muestre por pantalla si es mayor de edad o no.
"""

edad= int(input("Cual es tu edad?:"))
if edad >= 18:
  print("Eres mayor de edad")
else:
  print("Eres menor de edad")

"""### **Ejercicio 15**

Escribir un programa que almacene la cadena de caracteres "contraseña" en una variable, pregunte al usuario por la contraseña e imprima por pantalla si la contraseña introducida por el usuario coincide con la guardada en la variable sin tener en cuenta mayúsculas y minúsculas.
"""

contraseña= "contraseña"
contraseña_ingresada= input("Ingrese una contraseña:")
if(contraseña == contraseña_ingresada.lower()):
  print("Contraseña correcta")
else:
  print("Contraseña incorrecta")

"""### **Ejercicio 15**

Escribir un programa pida al usuario dos números enteros e informe por pantalla cual es menor de los dos, si son iguales, indicarlo por separado.

"""

num1= int(input("Ingrese un numero:"))
num2= int(input("Ingrese otro numero:"))
if(num1 < num2):
  print(f"El numero {num1} es menor")
elif(num1 == num2):
  print(f"Ambos numeros son iguales")
else:
   print(f"El numero {num2} es menor")

"""### **Ejercicio 16**

Escribir un programa que pida al usuario un número entero e indique si dicho número es par o impar.
"""

num= int(input("Ingrese un numero:"))
if(num % 2 == 0):
  print("El numero ingresado es par.")
else:
  print("El numero ingresado es inpar")

"""###**Ejercicio 17**

Para pagar un determinado impuesto se debe ser mayor de 18 años y tener unos ingresos iguales o superiores a $100000 mensuales. Escribir un programa que pregunte al usuario su edad y sus ingresos mensuales y muestre por pantalla si el usuario tiene que pagar o no.
"""

edad= int(input("Ingrese su edad: "))
ingresos= int(input("Ingrese sus ingresos mensuales: "))
if(edad > 18 and ingresos > 1000000):
  print("Debe pagar el impuesto")
else:
  print("No debe pagar el impuesto")

"""### **Ejercicio 18**

Escribir un programa que pida al usuario un número entero del 1 al 7 y muestre por pantalla el día de la semana correspondiente. Controlar que el número se encuentre en el rango correcto, si no es así, informar un error. Por ejemplo, si el número es 2 el día es martes.
"""

num= int(input("Ingrese un numero del 1 al 7: "))
if(num == 1):
  print("Lunes")
elif(num == 2):
  print("Martes")
elif(num == 3):
  print("Miercoles")
elif(num == 4):
  print("Jueves")
elif(num == 5):
  print("Viernes")
elif(num == 6):
  print("Sabado")
elif(num == 7):
  print("Domingo")
else:
  print("El numero ingresado no es correcto")

"""### **Ejercicio 19**

Las y los alumnas y alumnos de un curso se han dividido en dos grupos A y B de acuerdo al género y el nombre. El grupo A esta formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto. Escribir un programa que pregunte al usuario su inicial y género, y muestre por pantalla el grupo que le corresponde.
"""

inicial= ("Ingrese su unicial: ")
genero= ("Ingrese su genero: ")

"""### **Ejercicio 20**

Escribir un programa para una empresa que tiene salas de juegos para todas las edades y quiere calcular de forma automática el precio que debe cobrar a sus clientes por entrar. El programa debe preguntar al usuario la edad del cliente y mostrar el precio de la entrada. Si el cliente es menor de 4 años puede entrar gratis, si tiene entre 4 y 18 años debe pagar \$5 y si es mayor de 18 años, \$10.
"""

edad= int(input("Ingrese su edad: "))
if(edad < 4):
  print("Puede entrar gratis")
elif(edad >= 4 and edad <= 18):
  print("Debe pagar $5.")
else:
  print("Debe pagar $10")

"""### **Ejercicio 21**

Mostrar por pantalla todos los números enteros entre 1 y 100, hacerlo usando un bucle while y tambien con un bucle for.
"""

for i in range(1, 101):
  print(i)

rango = 1
while(rango <= 100):
  print(rango)
  rango+= 1

"""### **Ejercicio 22**

Escribir un programa que pida al usuario dos números enteros e imprima todos los números enteros entre ellos.
"""

num1= int(input("Ingrese un numero entero: "))
num2= int(input('Ingrese otro numero entero: '))

if(num1 < num2):
  for i in range((num1 + 1), (num2)):
    print(i)
else:
  for i in range((num2 + 1), (num1)):
    print(i)

"""### **Ejercicio 23**

Escribir un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantalla en líneas distintas el nombre del usuario tantas veces como el número introducido.
"""

name = input('Ingrese su nombre: ')
number = int(input('Ingrese un numero entero: '))

for i in range(number):
  print(name)

"""###**Ejercicio 24**

Escribir un programa que pida al usuario un número entero positivo y muestre por pantalla todos los números impares desde 1 hasta ese número.
"""

number = int(input('Ingrese un numero entero positivo: '))

for i in range(1, number):
  if(i % 2 != 0):
    print(i)

"""### **Ejercicio 25**

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo, de altura igual al número introducido.

Por ejemplo, si el usuario ingresa el numero 4:

\*

\* *

\* * *

\* * * *
"""

number = int(input('Ingrese un numero entero: '))
star = '*'
for i in range(number):
  print(star)
  star = star + '*'

"""### **Ejercicio 26**

Escribir un programa que imprima por pantalla todas las fichas del domino, una por línea, sin repetir.
"""

# prompt: Escribir un programa que imprima por pantalla todas las fichas del domino, una por línea, sin repetir.

fichas = []
for i in range(0, 7):
    for j in range(i, 7):
        fichas.append((i, j))

for ficha in fichas:
    print(ficha)

"""###**Ejercicio 27**

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo.

Si el usuario ingresa el numero 5:

1             

3 1           

5 3 1         

7 5 3 1       

9 7 5 3 1     
"""

number = int(input('Ingrese un numero entero: '))
odd = 1
tree = ''

for i in range(number):
  tree = str(odd) + tree
  print(tree)
  odd = odd + 2

"""
### **Ejercicio 28**

Escribir un programa que pida un número natural **N** al usuario e imprima por pantalla la suma de los números naturales de 1 hasta **N**.

Por ejemplo para **N = 5**, la salida debe ser:

1 + 2 + 3 + 4 + 5 = 15"""

number = int(input('Ingrese un numero natural: '))
plus = 0

for i in range(number + 1):
  plus += i

print(plus)

"""### **Ejercicio 29**

Construir un programa que lea un número natural **N** y calcule la suma de los primeros **N** números pares.
"""

number = int(input('Ingrese un numero natural: '))

if(number % 2 == 0):
  print(number + (number + 2))
else:
  print((number + 1) + (number + 3))

"""### **Ejercicio 30**

Escribir un programa que recibe como entrada desde el usuario dos números enteros e informa por pantalla todos los números pares entre ellos.
"""

num1 = int(input('Ingrese un numero entero: '))
num2 = int(input('Ingrese otro numero entero: '))

for i in range(num1, num2):
  if(i % 2 !=0):
    print(i)

"""### **Ejercicio 31**

Escribir un programa que pida un número entero y muestre por pantalla la cantidad de cifras de dicho número.
"""

num = input('Ingrese un numero entero: ')

print(len(num))

"""### **Ejercicio 32**

Escribir un programa que pida un número entero e informe si dicho numero es primo o no primo.
"""

num = int(input('Ingrese un numero entero: '))

for i in range (2, (num  - 1)):
  if(num % i == 0):
    print('No es un numero primo')
    break
  else:
    print('Es un numero primo')
    break